language: node_js
node_js:
  - "node"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - yarn run build.prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/code-challenger
  on:
    branch: master
